### ISSUE TITLE
Saving workspace with empty group (no views) causes crash

### ISSUE THREAD

**Issue by jmooney** [jmooney/EasyWorkspace-sublime#1]
If a user saves an easy workspace while one of the sublime groups has no views, EasyWorkspace crashes with an index error.

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "/home/jmooney2/.config/sublime-text-3/Packages/EasyWorkspace/easy-workspace.py", line 313, in run
    ws.buildFromWindow(self.window)
  File "/home/jmooney2/.config/sublime-text-3/Packages/EasyWorkspace/easy-workspace.py", line 250, in buildFromWindow
    group['active'] = sViews.index(activeSView)
ValueError: <sublime.View object at 0x7f935de2a950> is not in list
```

**Comment by jmooney** [comment]
Resolved on private branch. To be included in release.
