### ISSUE TITLE
An error on opening a workspace with certain name

### ISSUE THREAD

**Issue by certainlyakey** [jmooney/EasyWorkspace-sublime#10]
Hi! I've got this error on opening a workspace which name contains an em dash char (—):
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1034, in run_
    return self.run(**args)
  File "/Users/aleksandrb/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 411, in run
  File "/Users/aleksandrb/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 86, in loadFromFile
  File "/Users/aleksandrb/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 195, in buildFromJSON
TypeError: 'NoneType' object is not subscriptable
```

Apparently that's the only cause of the problem.

**Comment by jmooney** [comment]
Interesting, thanks for opening an issue. I'll take a look in the next day or two!

**Comment by jmooney** [comment]
Hi @certainlyakey . I wasn't able to replicate your issue with the current release. Including an em dash character in a workspace name seems to have no effect for me. Your issue looks like the workspace file is corrupted perhaps. 

For Mac OS X: All the workspace files are saved under the directory: "/Users/(your_user_name)/Library/Application Support/Sublime Text 3/Packages/EasyWorkspace-workspaces/"

You can also see this folder under the Sublime Menu "Preferences->Browse Packages". 

Can you take a look to see if the erroneous workspace file is saved here. If your workspace doesn't have any sensitive information (file paths), you're also welcome to attach here and I can take a closer look at what might be causing the issue.

**Comment by certainlyakey** [comment]
Hi! Thanks for the reply. 
I've taken a second attempt to reproduce it. This time an error has appeared on first save (not opening) of a workspace containing the em dash — 
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
  File "/Users/aleksandrb/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 335, in run
  File "/Users/aleksandrb/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 71, in saveToFile
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 144: ordinal not in range(128)
```
The workspace file gets saved with the correct filename (containing the em dash), but it's completely empty.

**Comment by jmooney** [comment]
Hi @certainlyakey. Thanks so much! It's obvious that somewhere in the code we're not using unicode properly. I'll take a look and get a fix back to you this weekend.

Thanks so much for pointing this out.

**Comment by jmooney** [comment]
Unfortunately, I was unable to repro this error :(. I tested across all three of my builds (PC, Mac OS X, LInux), and none had any trouble with unicode characters. Additionally, we are relying on sublime and Python to handle all the encoding for us, so I'm further at a loss of what debugging can be done.

Why would sublime (through EasyWorkspace) be encoding in ascii instead of unicode per its usual? Is your Python build perhaps different than the base included with sublime? 

For instance: https://stackoverflow.com/questions/42648808/unicode-encode-error-in-sublime-text-3-console 

I'll keep this open for now, but until I can effectively reproduce, I'm afraid I can't provide too much support :(. Please keep this ticket updated if you find any more details! Thanks again for all of your help so far.

**Comment by jmooney** [comment]
Closed due to inactivity and inability to reproduce. If another user experiences this same error, we can reopen with further investigation.
