### ISSUE TITLE
Bug: Error when opening workspace file

### ISSUE THREAD

**Issue by jmooney** [jmooney/EasyWorkspace-sublime#8]
My initial intuition is that this may have been caused by a 'temporary' file. That is, a file that was opened in preview mode in sublime was added or not added to the workspace.

Test workspace file causing the issue will be attached w/ paths redacted.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1034, in run_
    return self.run(**args)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 412, in run
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/EasyWorkspace.sublime-package/easy-workspace.py", line 157, in applyToWindow
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 312, in open_file
    return View(sublime_api.window_open_file(self.window_id, fname, flags, group))
TypeError: String required

**Comment by jmooney** [comment]
[TestCase.txt](https://github.com/jmooney/EasyWorkspace-sublime/files/2750747/TestCase.txt)

**Comment by jmooney** [comment]
If a workspace is saved with a temporary file open, that is a file not saved to disk, this error occurs. Saving the workspace with such a file introduces a 'null' value for the file's filename which causes this crash. 

The solution is to not save temporary/file-less files into the workspace.
